### PR TITLE
Update new engineer's urdf

### PR DESCRIPTION
**Pull request by ljq-lv**

### CODE REVIEW

**Comment by qiayuanl** [comment]
没图片我看个啥？

**Comment by ljq-lv** [comment]
Screenshot from 2022-05-19 11-06-29
Screenshot from 2022-05-19 11-06-47
Screenshot from 2022-05-19 11-06-55
Screenshot from 2022-05-19 11-07-01
Screenshot from 2022-05-19 11-07-10
Screenshot from 2022-05-19 11-07-25
Screenshot from 2022-05-19 11-07-37
Screenshot from 2022-05-19 11-10-11
Screenshot from 2022-05-19 11-10-18
Screenshot from 2022-05-19 11-10-23
Screenshot from 2022-05-19 11-10-41
Screenshot from 2022-05-19 11-10-55
Screenshot from 2022-05-19 11-12-50
Screenshot from 2022-05-19 11-12-56

**Comment by ljq-lv** [comment]
拖拽的惯量感觉有点问题 已经让机械重新出给我

**Comment by qiayuanl** [comment]
你在逗我吗？你这舵轮是什么东西？？？

**Comment by qiayuanl** [comment]
又来搞心态是吧？你他妈的瞎呀？

**Comment by qiayuanl** [comment]
拿去年步兵的舵轮拼到今年工程上面？

**Comment by ljq-lv** [comment]
Screenshot from 2022-05-20 01-25-21
Screenshot from 2022-05-20 01-25-06
Screenshot from 2022-05-20 01-24-52
Screenshot from 2022-05-20 01-24-42

**Comment by ljq-lv** [comment]
刷卡和拖拽 后面会有新的一版变动

**Comment by qiayuanl** [comment]
为什么又搞了新的舵轮文件？平衡步兵不是已经搞了舵轮了吗？

**Comment by ljq-lv** [comment]
嗷，这里我的问题，我没有update，没有看到平衡步兵新的那个舵轮文件，我弄好等等重新pr一下

**Pull request closed without merging**
