### PR TITLE
Updated new version sentry's urdf.

### PR DESCRIPTION
**Pull request by caijiefeng**

### CODE REVIEW

**Comment by caijiefeng** [comment]
Screenshot from 2022-06-05 20-06-31
Screenshot from 2022-06-05 20-07-22
Screenshot from 2022-06-05 20-08-05
Screenshot from 2022-06-05 20-08-13
初始姿态的视图以及其惯量

**Comment by caijiefeng** [comment]
Screenshot from 2022-06-05 20-09-37
Screenshot from 2022-06-05 20-10-47
Screenshot from 2022-06-05 20-10-56
Screenshot from 2022-06-05 20-11-00
Screenshot from 2022-06-05 20-14-02
Screenshot from 2022-06-05 20-14-11
上云台

**Comment by caijiefeng** [comment]
Screenshot from 2022-06-05 20-12-07
Screenshot from 2022-06-05 20-12-21
Screenshot from 2022-06-05 20-13-13
Screenshot from 2022-06-05 20-13-26
下云台

**Comment by caijiefeng** [comment]
Screenshot from 2022-06-05 20-15-13
Screenshot from 2022-06-05 20-16-37
Screenshot from 2022-06-05 20-16-44
Screenshot from 2022-06-05 20-16-49
Screenshot from 2022-06-05 20-17-41
Screenshot from 2022-06-05 20-18-20
Screenshot from 2022-06-05 20-18-59
Screenshot from 2022-06-05 20-19-12
Screenshot from 2022-06-05 20-19-24
Screenshot from 2022-06-05 20-19-52
底盘

**Comment by caijiefeng** [comment]
底盘的碰撞箱还在更新

**Comment by qiayuanl** [comment]
我看不到两个link之间的关键配合到底对不对，机械把关键的东西隐藏掉了
他估计不知道我在说什么，  @ye-luo-xi-tui @ljq-lv 你们告诉他

**Comment by caijiefeng** [comment]
Screenshot from 2022-06-07 09-58-17
Screenshot from 2022-06-07 09-58-21
Screenshot from 2022-06-07 09-58-32
Screenshot from 2022-06-07 09-58-57
Screenshot from 2022-06-07 09-59-04
碰撞箱

**Comment by caijiefeng** [comment]
> 我看不到两个link之间的关键配合到底对不对，机械把关键的东西隐藏掉了 他估计不知道我在说什么， @ye-luo-xi-tui @ljq-lv 你们告诉他

我不是很理解两个link间的关键配合具体指什么

**Comment by caijiefeng** [comment]
Screenshot from 2022-06-08 19-56-08
Screenshot from 2022-06-08 19-57-33
Screenshot from 2022-06-08 20-00-53
这样可以不

**Comment by ye-luo-xi-tui** [comment]
凯子哥在你的基础上改了一些，我close了merge他的

**Pull request closed without merging**
